/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QualificacoesRouteImport } from './routes/qualificacoes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AdmissoesRouteImport } from './routes/admissoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlataformaPortalLoginRouteImport } from './routes/plataforma.portal.login'
import { Route as PlataformaBibliotecaLoginRouteImport } from './routes/plataforma.biblioteca.login'

const QualificacoesRoute = QualificacoesRouteImport.update({
  id: '/qualificacoes',
  path: '/qualificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissoesRoute = AdmissoesRouteImport.update({
  id: '/admissoes',
  path: '/admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaPortalLoginRoute = PlataformaPortalLoginRouteImport.update({
  id: '/plataforma/portal/login',
  path: '/plataforma/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaBibliotecaLoginRoute =
  PlataformaBibliotecaLoginRouteImport.update({
    id: '/plataforma/biblioteca/login',
    path: '/plataforma/biblioteca/login',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contacto': typeof ContactoRoute
  '/qualificacoes': typeof QualificacoesRoute
  '/plataforma/biblioteca/login': typeof PlataformaBibliotecaLoginRoute
  '/plataforma/portal/login': typeof PlataformaPortalLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contacto': typeof ContactoRoute
  '/qualificacoes': typeof QualificacoesRoute
  '/plataforma/biblioteca/login': typeof PlataformaBibliotecaLoginRoute
  '/plataforma/portal/login': typeof PlataformaPortalLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contacto': typeof ContactoRoute
  '/qualificacoes': typeof QualificacoesRoute
  '/plataforma/biblioteca/login': typeof PlataformaBibliotecaLoginRoute
  '/plataforma/portal/login': typeof PlataformaPortalLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissoes'
    | '/contacto'
    | '/qualificacoes'
    | '/plataforma/biblioteca/login'
    | '/plataforma/portal/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissoes'
    | '/contacto'
    | '/qualificacoes'
    | '/plataforma/biblioteca/login'
    | '/plataforma/portal/login'
  id:
    | '__root__'
    | '/'
    | '/admissoes'
    | '/contacto'
    | '/qualificacoes'
    | '/plataforma/biblioteca/login'
    | '/plataforma/portal/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissoesRoute: typeof AdmissoesRoute
  ContactoRoute: typeof ContactoRoute
  QualificacoesRoute: typeof QualificacoesRoute
  PlataformaBibliotecaLoginRoute: typeof PlataformaBibliotecaLoginRoute
  PlataformaPortalLoginRoute: typeof PlataformaPortalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qualificacoes': {
      id: '/qualificacoes'
      path: '/qualificacoes'
      fullPath: '/qualificacoes'
      preLoaderRoute: typeof QualificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissoes': {
      id: '/admissoes'
      path: '/admissoes'
      fullPath: '/admissoes'
      preLoaderRoute: typeof AdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/portal/login': {
      id: '/plataforma/portal/login'
      path: '/plataforma/portal/login'
      fullPath: '/plataforma/portal/login'
      preLoaderRoute: typeof PlataformaPortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/biblioteca/login': {
      id: '/plataforma/biblioteca/login'
      path: '/plataforma/biblioteca/login'
      fullPath: '/plataforma/biblioteca/login'
      preLoaderRoute: typeof PlataformaBibliotecaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissoesRoute: AdmissoesRoute,
  ContactoRoute: ContactoRoute,
  QualificacoesRoute: QualificacoesRoute,
  PlataformaBibliotecaLoginRoute: PlataformaBibliotecaLoginRoute,
  PlataformaPortalLoginRoute: PlataformaPortalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
