/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QualificacoesRouteImport } from './routes/qualificacoes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AdmissoesRouteImport } from './routes/admissoes'
import { Route as IndexRouteImport } from './routes/index'

const QualificacoesRoute = QualificacoesRouteImport.update({
  id: '/qualificacoes',
  path: '/qualificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissoesRoute = AdmissoesRouteImport.update({
  id: '/admissoes',
  path: '/admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contacto': typeof ContactoRoute
  '/qualificacoes': typeof QualificacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contacto': typeof ContactoRoute
  '/qualificacoes': typeof QualificacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contacto': typeof ContactoRoute
  '/qualificacoes': typeof QualificacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admissoes' | '/contacto' | '/qualificacoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admissoes' | '/contacto' | '/qualificacoes'
  id: '__root__' | '/' | '/admissoes' | '/contacto' | '/qualificacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissoesRoute: typeof AdmissoesRoute
  ContactoRoute: typeof ContactoRoute
  QualificacoesRoute: typeof QualificacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qualificacoes': {
      id: '/qualificacoes'
      path: '/qualificacoes'
      fullPath: '/qualificacoes'
      preLoaderRoute: typeof QualificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissoes': {
      id: '/admissoes'
      path: '/admissoes'
      fullPath: '/admissoes'
      preLoaderRoute: typeof AdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissoesRoute: AdmissoesRoute,
  ContactoRoute: ContactoRoute,
  QualificacoesRoute: QualificacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
